Algoritmo "Trabalhando variáveis"

Var
   palavra1, palavra2, palavra3: caractere
   numero1, numero2, numero3: inteiro

Inicio
   escreval ("Digite palavra1: ")
   leia (palavra1)
   escreval ("Digite palavra2: ")
   leia (palavra2)
   escreval ("Digite numero1: ")
   leia (numero1)
   escreval ("Digite numero2: ")
   leia (numero2)
   palavra3 <- palavra1 + palavra2
   numero3 <- numero1 + numero2
   escreval (palavra3)
   escreval (numero3)

Fimalgoritmo